"""Generate Unicode character classes.

Python versions use different Unicode versions, so generating these classes
keeps linkify behavior consistent across supported Python versions.

Run this script with the newest supported CPython::

    python support/generate_ucre.py
"""

import re
import sys
import unicodedata
from collections.abc import Iterator
from pathlib import Path

TARGET = Path(__file__).resolve().parent.parent / "linkify_it" / "_ucre_data.py"

MAX_CODE_POINT = 0x110000

# Generated name -> Unicode General_Category prefix.
CATEGORIES = {
    "SRC_CC": "Cc",
    "SRC_CF": "Cf",
    "SRC_P": "P",
    "SRC_Z": "Z",
}

HEADER = '''"""Unicode character classes for :mod:`linkify_it.ucre`.

Generated by ``support/generate_ucre.py`` from Unicode {version}.
Do not edit by hand.
"""

UNIDATA_VERSION = "{version}"

# Match any single character, including newlines.
SRC_ANY = "[\\\\s\\\\S]"
'''


def ranges_for(prefix: str) -> Iterator[tuple[int, int]]:
    """Yield (first, last) code point ranges whose category starts with prefix."""
    start: int | None = None
    previous = 0

    for code_point in range(MAX_CODE_POINT):
        if not unicodedata.category(chr(code_point)).startswith(prefix):
            continue

        if start is None:
            start = previous = code_point
        elif code_point == previous + 1:
            previous = code_point
        else:
            yield start, previous
            start = previous = code_point

    if start is not None:
        yield start, previous


def escape(code_point: int) -> str:
    """Escape a code point for use inside a character class.

    `re.escape` is what makes this safe: the class has to survive characters
    that are meaningful to the regexp engine, `]` and `\\` above all.
    """
    return re.escape(chr(code_point))


def as_literal(text: str) -> str:
    """Render text as an ASCII-only, double-quoted Python literal.

    `ascii()` reaches for single quotes, which black would rewrite.
    """
    literal = ascii(text)
    if literal.startswith('"'):
        return literal

    body = literal[1:-1].replace("\\'", "'").replace('"', '\\"')

    return f'"{body}"'


def char_class(prefix: str) -> str:
    """Build a character class string covering one category prefix."""
    parts = []
    for first, last in ranges_for(prefix):
        if first == last:
            parts.append(escape(first))
        else:
            parts.append(f"{escape(first)}-{escape(last)}")

    return "[" + "".join(parts) + "]"


def main() -> int:
    version = unicodedata.unidata_version
    print(f"python {sys.version.split()[0]}, Unicode {version}")

    chunks = [HEADER.format(version=version)]
    for name, prefix in CATEGORIES.items():
        source = char_class(prefix)
        chunks.append(
            f"\n# General_Category={prefix}\n"
            f"{name} = {as_literal(source)}  # noqa: E501\n"
        )
        print(f"  {name:<8} ({prefix}): {len(source)} chars")

    TARGET.write_text("".join(chunks), encoding="utf-8", newline="\n")
    print(f"wrote {TARGET}")

    return 0


if __name__ == "__main__":
    main()
