# name: CI

# on:
#   push:
#     branches: [main]
#     tags:
#       - "v*"
#   pull_request:

# jobs:
#   sphinx-build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v2
#       - name: Set up Python 3.7
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.7
#       - name: Install dependencies
#         run: |
#           pip install .[doc]
#       - name: sphinx apidoc
#         run: |
#           sphinx-apidoc -f -o ./docs .
#       - name: sphinx build
#         run: |
#           sphinx-build -nW --keep-going -b html docs/ docs/_build/html

# ToDo: pushlish rtd
# publish:
#   runs-on: ubuntu-latest
